# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: QQQR

on: 
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/setup-node@v2.4.0
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -e .[captcha]

      - name: Test with pytest
        env:
          TEST_UIN: ${{ secrets.TEST_UIN }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          export PYTHONPATH=$(pwd)/src
          python -m pytest test/test_up.py test/test_captcha.py
